import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/common/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<main className="flex flex-col items-center">
						<div className="w-full px-6 flex justify-center md:pr-20 md:pl-20 mt-10">
							<Header />
						</div>
						{children}
					</main>

				</Providers>
			</body>
		</html>
	);
}